# Generated by Django 4.0.3 on 2022-04-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
    ]
