# Generated by Django 4.0.3 on 2022-04-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
